### ISSUE TITLE
KeyError: "first_name" when calling `workos.sso.SSO.get_profile_and_token`

### ISSUE THREAD

**Issue by Genetical** [workos-inc/workos-python#102]
WorkOS Version: `1.6.0`
Django Version: `3.2.9`
Python Version: `3.9.9`

Successful passwordless session (magic link auth) flows are failing when calling `get_profile_and_token` because the API is not returning `first_name` and `last_name`. This means that during the iteration of `cls.OBJECT_FIELDS` in `workos.resources.base.WorkOSBaseResource.construct_from_response`, the `setattr` function is attempting to access a field in the response dictionary that doesn't exist, hence the `KeyError`.

This is not part of a provider (e.g: Google SSO) SSO process and as such, no `first_name` or `last_name` should be expected as WorkOS would not know these values.

Below is the traceback along with relevant local variables.
**Traceback:**
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "<... SNIP ...>", line 22, in get
    auth_service.login_user_with_code(code_str=login_code_str, request=request)
  File "/opt/project/authentication/auth_service.py", line 64, in login_user_with_code
    profile_and_token_instance = workos_client.sso.get_profile_and_token(code_str)
  File "/usr/local/lib/python3.9/site-packages/workos/sso.py", line 132, in get_profile_and_token
    return WorkOSProfileAndToken.construct_from_response(response)
  File "/usr/local/lib/python3.9/site-packages/workos/resources/sso.py", line 41, in construct_from_response
    profile_and_token.profile = WorkOSProfile.construct_from_response(
  File "/usr/local/lib/python3.9/site-packages/workos/resources/base.py", line 22, in construct_from_response
    setattr(obj, field, response[field])
```

**Local Vars**
```python
response = {
 'connection_id': 'conn_*********',
 'connection_type': 'MagicLink',
 'email': '*********',
 'id': 'prof_*********',
 'idp_id': '',
 'object': 'profile',
 'organization_id': 'org_*********',
 'raw_attributes': {}
}

obj.OBJECT_FIELDS = [
 'id',
 'email',
 'first_name',
 'last_name',
 'organization_id',
 'connection_id',
 'connection_type',
 'idp_id',
 'raw_attributes'
]
```

**Comment by maxdeviant** [comment]
Hey there @Genetical, we're taking a look into this now.

It appears that there was an unintentional change with the structure of the profile response that is causing the breakage in the Python SDK.

We'll be putting a fix into production shortly.

**Comment by maxdeviant** [comment]
@Genetical A new version of the API has been deployed with a fix for the regression. Could you verify that it has resolved the issue you were seeing?

Additionally, I've opened #103 to resolve the `KeyError` issue in the case where a field is missing from the response.

**Comment by Genetical** [comment]
That seems to have fixed it, thank you for the quick response and fix.
