### ISSUE TITLE
BadRequest error 

### ISSUE THREAD

**Issue by kareemcoding** [workos-inc/workos-python#93]
**Reproduce**

Call the `get_profile_and_token` method with an expired/invalid code.

**Traceback**

```python
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
web_1       |     self.result = application(self.environ, self.start_response)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
web_1       |     return self.application(environ, start_response)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
web_1       |     response = self.get_response(request)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
web_1       |     response = self._middleware_chain(request)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
web_1       |     response = response_for_exception(request, exc)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
web_1       |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
web_1       |     return debug.technical_500_response(request, *exc_info)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
web_1       |     html = reporter.get_traceback_html()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 346, in get_traceback_html
web_1       |     return t.render(c)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
web_1       |     return self._render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_1       |     return self.nodelist.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1       |     bit = node.render_annotated(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
web_1       |     return nodelist.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1       |     bit = node.render_annotated(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 211, in render
web_1       |     nodelist.append(node.render_annotated(context))
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 246, in render
web_1       |     return nodelist_true_output or self.nodelist_true.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1       |     bit = node.render_annotated(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
web_1       |     return nodelist.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1       |     bit = node.render_annotated(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
web_1       |     return nodelist.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1       |     bit = node.render_annotated(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1       |     return self.render(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 988, in render
web_1       |     output = self.filter_expression.resolve(context)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 698, in resolve
web_1       |     new_obj = func(obj, *arg_vals)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/template/defaultfilters.py", line 42, in _dec
web_1       |     args[0] = str(args[0])
web_1       |   File "/usr/local/lib/python3.9/site-packages/workos/exceptions.py", line 38, in __str__
web_1       |     if self.error_description is not None:
web_1       | AttributeError: 'BadRequestException' object has no attribute 'error_description'

```

**Configuration**

```python
[tool.poetry]
name = "alpha"
version = "0.1.0"
description = "Unified framework for ihorizon applications."
authors = ["Che Sampat <che@ihorizon.co.uk>", "Arion Sejdia <arion.sejdia@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.7"
dj-database-url = "^0.5.0"
python-dotenv = "^0.19.0"
sentry-sdk = "^1.3.1"
whitenoise = "^5.3.0"
psycopg2 = "^2.9.1"
django-health-check = "^3.16.4"
django-anymail = "^8.4"
celery = {extras = ["redis"], version = "^5.1.2"}
psycopg2-binary = "^2.9.1"
django-crispy-forms = "^1.13.0"
workos = "^1.4.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by johntmyers** [comment]
Yep getting the same thing: https://github.com/workos-inc/workos-python/issues/94

Need to set the attr value on init.

**Comment by blairlunceford** [comment]
​I pushed a fix in the latest patch release of the Python SDK, 1.4.1, can you test with this new version?
​
​https://github.com/workos-inc/workos-python/releases/tag/v1.4.1
​
​Thanks!
